### ISSUE TITLE
Server side code

### ISSUE THREAD

**Issue by MarioIannotta** [willpowell8/LocalizationKit_iOS#1]
Hi, this is a really cool work!
Are you going to release the server side code too? 
Thanks.

**Comment by haemi** [comment]
would be great because of ATS; or move the server to https in case  disables ATS...

**Comment by willpowell8** [comment]
Thanks for the comments. I have moved the system over to https so it should work without ATS exclusion. I am working on the server side code and UI, the version I have built for https://www.localizationkit.com/app is working against a serverless architecture so it gives global scalability with datacenter replication and low latency regardless of users. However I am working on getting a version that can be self hosted. Im looking to support Mysql, Sqlite, MSSql and PostgreSQL as the database. @MarioIannotta and @haemi what are your server stacks you use?

**Comment by Tripwire999** [comment]
I'm also very interested in the Server side code!

**Comment by MarioIannotta** [comment]
@willpowell8 currently I'm using a LAMP stack.

**Comment by willpowell8** [comment]
Will update the project when this is released
