### ISSUE TITLE
Delete key is not working

### ISSUE THREAD

**Issue by OuSS-90** [willpowell8/LocalizationKit_iOS#13]
I click on delete but the key stay

**Comment by willpowell8** [comment]
Thank you for raising this. Looks like my last web update has broken it. I will look into it.

**Comment by JesseSchneider** [comment]
Hey do you know when this will be fixed. I'm having the same issue. I added a test key on the web portal for my project, but I'm unable to delete it. :(

**Comment by zxl777** [comment]
Please Fix this bug,thank you.

**Comment by willpowell8** [comment]
Yes the web ui update in the next week will resolve this.

**Comment by hunasdf** [comment]
+1, Delete button does not work on the web

**Comment by willpowell8** [comment]
This is fixed
