### ISSUE TITLE
what is the difference between this and lokalise?

### ISSUE THREAD

**Issue by rlam3** [willpowell8/LocalizationKit_iOS#14]
this looks pretty cool. but how many languages can we localize? this looks similar to  https://lokalise.co/en

**Comment by willpowell8** [comment]
You can localise any language in ISO 639 list [wikipedia list here](https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes)

There are other solutions out there for localization over the air delivery. Localizationkit is built from ground up for swift and does a realtime as you type in the web page it updates in app (if you have turned live updates on). 

Taking a quick look at the lokalise framework developed they use swizzling to add some of their functions into your app. On the whole swizzling is frowned on as an approach as it is not reliable as can lead to an unstable state, app being rejected by Apple during approval process and can be blocking when iOS updates. I don't know this framework but it does look to have a strong translation platform behind it. 

Localizationkit is also open source for the part that goes in your app so you can see what code you are putting in your app.

At the end of the day I would say try the localization solutions out and see what works best for your projects.

**Comment by willpowell8** [comment]
There is no limit on number of strings that localization kit can handle.
