### ISSUE TITLE
Please Add some example on 'how to use Localization Event with code'

### ISSUE THREAD

**Issue by delmarz** [willpowell8/LocalizationKit_iOS#15]
Can you add an example of how to use Localization Event with code, when the value of a key is updated online?

**Comment by willpowell8** [comment]
Hi @delmarz, I have written a wiki for how you use the Localization events:
[Localization Events Wiki](https://github.com/willpowell8/LocalizationKit_iOS/wiki/Localization-Events)

Hope this helps
