### ISSUE TITLE
LocalizationKit translation bugs

### ISSUE THREAD

**Issue by steelzeh** [willpowell8/LocalizationKit_iOS#17]
The website is very buggy, i once sat and translated over 100 keys in one go, and it only saved 30 or so, and some of them were not saved fully so some translations would be saved with missing characters.

e.g "Full amount" was once saved as "Full a", it's like it saved before i have finished entering the full translation.

**Comment by willpowell8** [comment]
Apologies for this I will look into it.

**Comment by abdualrhmanio** [comment]
yes me to
the problem now my app in production :( 
many keys are rested

**Comment by willpowell8** [comment]
Hi, there was a bug in the localization saving system which I have found causing some keeps to not save if you type rapidly. Thank you for raising this.

**Comment by willpowell8** [comment]
I have updated the web system to improve reliability.
