### ISSUE TITLE
Updates to the app Live on AppStore

### ISSUE THREAD

**Issue by imRanjit** [willpowell8/LocalizationKit_iOS#18]
Hi WillPowell,
I am just exploring this lib, and it looks mindblowing. I had one doubt, by "live update" does it mean that it will update the strings on the app which is already Live on app store?

**Comment by willpowell8** [comment]
Yes it will mean that strings are updated. I would say that I advise using the live update for development and turn it off for releases versions. If you do turn off live updates you will still get the updates but on app restart.
