### ISSUE TITLE
Use IETF language tags instead of the pure ISO 639

### ISSUE THREAD

**Issue by Felizolinha** [willpowell8/LocalizationKit_iOS#21]
Apple uses IETF for their Language and Locale IDs, it basically includes region denominators along with the language denominators, from what I understand. This would be a really great addition, as localization might differ from a region to another.

Not having a region identifier is bad because some regions use the same languages differently. Portuguese, for example, has different meanings for MANY words used in Portugal and Brazil. Cases like these could easily be solved by using IETF, just like Apple does it.

**Comment by willpowell8** [comment]
Hi, Thank you for this. I have been applying updates to support the IETF language code set so now you can select languages like zh-Hans-TW, when you select a language there is a list of regions that you can add. I will finish loading the regions list. Note that it use fallbacks. For instance you can set an en language and then en-US but if you were to come from en-UK it would revert to en language set.
