### ISSUE TITLE
Language.localizedName not working as expected.

### ISSUE THREAD

**Issue by Felizolinha** [willpowell8/LocalizationKit_iOS#22]
I tested the attribute for English, Spanish and Portuguese. Spanish and Portuguese return language keys instead of the localized name when calling this attribute, and I believe many other languages have the same behavior. I understand some of the languages might not be localized yet, but I believe it would be better to default to the English names in these cases, instead of language codes.

**Comment by willpowell8** [comment]
Thank you for the feedback I will update this

**Comment by willpowell8** [comment]
I have added more of the localized name and tweaked the dataflow in latest version
