### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by skrew** [willpowell8/LocalizationKit_iOS#25]
Hi,

`socket.io-client-swift` (dependency) are Swift 4 support.

Thanks

**Comment by willpowell8** [comment]
Hi Skrew, I have created a new branch. https://github.com/willpowell8/LocalizationKit_iOS/tree/swift4 which supports swift 4 for getting the values. 

However currently the live update from web page doesn't work as I need to apply the socketio 2.0 patches to the backend website to support the changes.

**Comment by willpowell8** [comment]
@skrew  the master is now on Swift 4 with all swift 4 dependencies.
