### ISSUE TITLE
Localization.resetToDeviceLanguage() is broken

### ISSUE THREAD

**Issue by SergejLogis** [willpowell8/LocalizationKit_iOS#26]
It seems like there is an issue with `Localization.resetToDeviceLanguage()` method - it is currently written like this:
```
public func resetToDeviceLanguage(){
    self.resetToDeviceLanguage();
}
```
Which, from my understanding, will simply result in an infinite loop and crash. According to the documentation, this method should be `static`, but I can't find such in the code. 🤔

**Comment by willpowell8** [comment]
@SergejLogis thank you for finding this. I have resolved in release 3.0.1, which goes along with the networking updates.

The Website live updates aren't working on the 3.x releases yet, load is working correctly. I will doing the web page update this week.
