### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [willpowell8/LocalizationKit_iOS#3]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by willpowell8** [comment]
Good thought I will get it supported ASAP.

**Comment by OmarCaf** [comment]
@willpowell8 any news about carthage compatibility?

**Comment by PPacie** [comment]
Hi Will, do you know when Carthage will be supported? 

Thanks in advance.

**Comment by willpowell8** [comment]
Sorry this has taken me so long. I needed to get round to restructuring the project. Now you should be able to use with Carthage:
`github "willpowell8/LocalizationKit_iOS`
