### ISSUE TITLE
Error in the site "502 Bad Gateway"

### ISSUE THREAD

**Issue by cs4alhaider** [willpowell8/LocalizationKit_iOS#32]
I'm trying to open this page and it give my an error "502 Bad Gateway" https://www.localizationkit.com/app/

**Comment by RayanSaeed** [comment]
+1

**Comment by akaru** [comment]
Same for me

**Comment by willpowell8** [comment]
This was resolved. A meltdown patch being applied caused the UI servers to have an issue.
