### ISSUE TITLE
Changing language after UI is loaded, won't refresh the labels in tableview

### ISSUE THREAD

**Issue by iPhoNewsRO** [willpowell8/LocalizationKit_iOS#35]
Hello, i am using LocalizationKit for a personal project and i implemented my app around it. Now i want to implement some kind of instant app language changer.. so i use 

`Localization.setLanguage("rm")` and `Localization.setLanguage("en")`

but the strings are not updated. i tried with a tableview and tabbar controller

also, why don't you use the standard code languages? Romanian should be RO instead of RM

Thanks

**Comment by iPhoNewsRO** [comment]
Later edit: for the first time, it looks like at the second tap, the language switch is happening. However, then it will always work on the first time.

my code: 
`if Localization.languageCode == "en" {
            Localization.setLanguage("rn")
        } else {
            Localization.setLanguage("en")
        }
        
        self.reloadData()`

this is called at `didSelectRowAt`. 

Thanks

**Comment by willpowell8** [comment]
Hi iPhoNewsRo, Thank you for your feedback. I will look into this.

I believe the system is using rm - Romansh and ro - Romanian; Moldavian; Moldovan. Can you provide me a screenshot of where you see the issue of it using the wrong code? You can direct email me at willpowell (number eight) [at] gmail.com

**Comment by iPhoNewsRO** [comment]
i made sure to call the language codes the correct way, but the issue still exists:

1. run the app and call:

```
if Localization.language?.key == "en" {
            Localization.setLanguage("ro")
        } else {
            Localization.setLanguage("en")
        }
```

2. the first time you call that code (tap a button), it won't work and won't do anything
3. after the first tap, the system will work as expected.

i can provide my project if you want to debug. thanks, Will!

**Comment by iPhoNewsRO** [comment]
i changed the flow of my app a bit so this isn't an issue anymore. indeed i was using `rn` instead of `ro` but i also had to reload my views (tabbar items for example)
thanks!

**Comment by willpowell8** [comment]
Are you setting the LocalizationKey on the UI component? Or using localization.get?
