### ISSUE TITLE
How safe is this? What's the privacy policy?

### ISSUE THREAD

**Issue by etherwatch** [willpowell8/LocalizationKit_iOS#39]
Can't find info on this anywhere so posting here. This looks amazing and I want to use it, only concern is privacy and how data is handled? What if the dashboard is hacked -- doesn't this put the content of every app at risk if someone were to change the strings, etc?

**Comment by willpowell8** [comment]
Hi, Apologies for a late reply. The dashboard UI is password protected. The backend is also backing up the strings daily so we can restore a backup if something was to go wrong.
