### ISSUE TITLE
Question: Obj-C support?

### ISSUE THREAD

**Issue by oferRounds** [willpowell8/LocalizationKit_iOS#4]
Hi @willpowell8,

Looks AMAZING! Way to go!

One question though: can I use this library within a Obj-C project?

**Comment by willpowell8** [comment]
Hi, I have just tried adding it to an Obj-C project and there are some issues with the Swift bridging header which needs resolving. I will sort it out for you.

**Comment by oferRounds** [comment]
Thanks, I would be very happy! Thank you! :-)

**Comment by DoctorG** [comment]
Me too!

**Comment by vbklv** [comment]
Is the Obj-C compatibility issue now solved?

**Comment by tylerjames** [comment]
Localization is so terrible in Xcode in general and in Objective C especially. It would be really nice to be able to use something like this

**Comment by willpowell8** [comment]
Hi All, @tylerjames  @vbklv @DoctorG @oferRounds  apologies it has take me a while to resolve this. I have restructured the application and added an objective c example. I have also created a wiki page:

[Objective C Localization Wiki](https://github.com/willpowell8/LocalizationKit_iOS/wiki/Objective-C---Localization-Kit-Example)
