### ISSUE TITLE
Example - Error: Argument Labels '(appKey:, useSettings:)' do not match any available overloads

### ISSUE THREAD

**Issue by DexVitalitY** [willpowell8/LocalizationKit_iOS#6]
Hi there,

The idea of this App sounds awesome. I cloned the project to try out the example app but upon trying to build out the app I cannot get the App to Build.

I get the Swift Compiler Error, xCode had to Convert to Current Swift Syntax before I tried building.

**Comment by willpowell8** [comment]
Thanks for the support.

This seems to have been caused by an issue in the SocketIO dependency, which I have updated in 1.1.2 commit. Try cloning a new version and compiling that, let me know how you get on. Many thanks Will
