### ISSUE TITLE
Missing function Localization.availableLanguages

### ISSUE THREAD

**Issue by sidetrax** [willpowell8/LocalizationKit_iOS#8]
Thanks for your great project. I immediately loved it. ;-)

You mentioned Localization.availableLanguages in your Readme file.
But in Xcode this is not available.
Is there a problem on my end or do others have this as well?

**Comment by willpowell8** [comment]
Yes you should be able to see it in the example app. Are you able to do a **pod update** and tell me which version you are using?

**Comment by sidetrax** [comment]
Thanks for your help. ;-)
When running pod update it worked and installed it.
I could use it before without the availableLanguages method.

Issue resolved.
