### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by cre8it** [willpowell8/LocalizationKit_iOS#9]
Hi

how is your library dealing with offline capabilities. For example when a mobile client is not connected to the internet but had already once a successful connection to the localization backend?

How about when the client never had a connection?

thanks for feedback

**Comment by tolgaarikan** [comment]
Your first question is answered on README.

**Caching**

LocalizationKit internalizes the caching of the localizations and translations that you have translated. Currently once a languages is loaded from the server it is stored locally for offline and subsequent use. It is updated everytime the app is reopened where by the local version is first loaded and then replaced by the server version.

**Comment by willpowell8** [comment]
Thank you for answering this. Think this issue is closed.
